config/routes.rb
Rails.application.routes.draw do

  # This is the action for the root route
  root 'public#index'

  get 'public/index'
  # rails doesnt know how to make this a route, so you can tell it with as
  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  # Simple routes since there are no models, DB, etc. for this.
  get 'admin', :to => 'access#menu'
  get 'access/menu'   #index
  get 'access/login'  #new
  post 'access/attempt_login'
  get 'access/logout'


# ~~~> Subjects Routes <~~~
# These routes were provided by default from the rails generate command.
# Using resourceful routes instead.
#  get 'subjects/index'
#  get 'subjects/show'
#  get 'subjects/new'
#  get 'subjects/edit'
#  get 'subjects/delete'

  resources :subjects do

    member do
      get :delete
    end

  end

# ~~~> Pages Routes <~~~~
#  get 'pages/index'
#  get 'pages/show'
#  get 'pages/new'
#  get 'pages/edit'
#  get 'pages/delete'

  resources :pages do

    member do
      get :delete
    end

    collection do
      get :index_by_subject
    end

  end

# ~~~> Section Routes <~~~
#  get 'sections/index'
#  get 'sections/show'
#  get 'sections/new'
#  get 'sections/edit'
#  get 'sections/delete'

  resources :sections do

    member do
      get :delete
    end

    collection do
      get :index_by_page
    end

  end

# ~~~~> Admin User Routes <~~~~
#  get 'admin_user/index'
#  get 'admin_user/new'
#  get 'admin_user/create'
#  get 'admin_user/edit'
#  get 'admin_user/update'
#  get 'admin_user/delete'
#  get 'admin_user/destroy'

  resources :admin_user, :except => 'show' do

    member do
      get :delete
    end

  end


  # simple match routes
  # match "demo/index", :to => "demo#index", :via => :get
  # this is the longer way to write the same.

  # Default route may go away in future versions of Rails.
  # get ':controller(/:action(/:id))'
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
  get 'demo/escape_output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Page form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Permalink</th>
    <td><%= f.text_field(:permalink) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@page_count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Subject (non-editible)</th>
    <td><%= f.object.subject.name %></td>
  </tr>
<!--  <tr>
    <th>Subject</th>
    <td><%# f.select(:subject_id, @subjects.map {|s| [s.name, s.id]}) %></td>
  </tr> -->
</table>

app/views/pages/delete.html.erb
<%= link_to("<< Back to Subjects", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages delete">
  <h2>Delete Page</h2>
  <!-- Can leave the url out, but MUST specify action (delete in this case) -->
  <%= form_for(@page, :url => page_path(@page, :subject_id => @subject.id), :method => 'delete') do |f| %>

    <p> Are you SURE you want to permanently delete this page?</p>

    <p class="reference-name>"><strong><%= f.object.name %></strong></p>

    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>

  <% end %>
</div>

<p><i>Find me in app/views/pages/delete.html.erb</i></p>

app/views/pages/edit.html.erb
<%= link_to("<< Back to Subjects", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages edit">

  <h2>Update Page</h2>
  <%= form_for(@page, :url => page_path(@page, :subject_id => @subject.id)) do |f| %>

<!-- Moved to _form partial....
    <table summary="Page form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Permalink</th>
        <td><%= f.text_field(:permalink) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible?</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
      <tr>
        <th>Subject</th>
        <td><%= f.text_field(:subject_id) %></td>
      </tr>
    </table>  -->

    <%= render(:partial => 'form', :locals =>{:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Page") %>
    </div>

  <% end %>
</div>

<p><i>Find me in app/views/pages/edit.html.erb</i></p>

app/views/pages/index.html.erb
<% @page_title = "All Pages" %>

<%= link_to("<<Back to Subjects", subjects_path, :class => 'back-link') %>

<!-- label controller and action-->
<div class="pages index">
  <h2>Pages</h2>

<!--  <%= link_to("Add New Page", 'page/new', :class => 'action new') %> -->
  <p></i><%= link_to("Pages can only be added from the index_by_subject view", subjects_path) %> </i></p>

  <table class="listing" summary="Page list">
    <!-- This assigns the header row -->
    <tr class="header">
      <th>#</th>
      <th>Page</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Subject ID</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <!-- This each method will will go through every element in the array and assign it to the local block value |page|. -->
    <% @pages.each do |page| %>
    <tr> <!-- Table row -->
      <td><%= page.position %></td> <!-- Table data -->
      <td><%= page.name %></td>
      <td><%= page.permalink %></td>
      <td class="center"><%= status_tag(page.visible) %></td>
      <td class="center"> <%= link_to("#{page.subject_id}", {:controller => 'subjects', :action => 'show', :id => page.subject_id}, :class => 'action show') %> </td>
      <td class="center"><%= page.sections.size %></td>
      <td class="actions">
        <%= link_to("View Sections", index_by_page_sections_path(:page_id => page.id), :class => 'action index_by_page') %>
        <%= link_to("Show", page_path(page, :subject_id => page.subject_id), :class => 'action show') %>
        <%= link_to("Edit", edit_page_path(page, :subject_id => page.subject_id), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page, :subject_id => page.subject_id), :class => 'action delete') %>
      </td>
    </tr>

    <% end %>
  </table>
</div>

<p><i>Find me in app/views/pages/index.html.erb</i></p>

app/views/pages/index_by_subject.html.erb
<% @page_title = "All Pages" %>

<%= link_to("<<Back to Subjects", subjects_path, :class => 'back-link') %>

<!-- label controller and action-->
<div class="pages index">
  <h2>Pages</h2>

<!--  <%= link_to("Add New Page", 'page/new', :class => 'action new') %> -->
  <%= link_to("Add New Page", new_page_path(:subject_id => @subject.id), :class => 'action new') %>

  <table class="listing" summary="Page list">
    <!-- This assigns the header row -->
    <tr class="header">
      <th>#</th>
      <th>Page</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Subject ID</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <!-- This each method will will go through every element in the array and assign it to the local block value |page|. -->
    <% @pages.each do |page| %>
    <tr> <!-- Table row -->
      <td><%= page.position %></td> <!-- Table data -->
      <td><%= page.name %></td>
      <td><%= page.permalink %></td>
      <td class="center"><%= status_tag(page.visible) %></td>
      <td class="center"> <%= link_to("#{page.subject_id}", {:controller => 'subjects', :action => 'show', :id => page.subject_id}, :class => 'action show') %> </td>
      <td class="center"><%= page.sections.size %></td>
      <td class="actions">
        <%= link_to("View Sections", index_by_page_sections_path(:page_id => page.id), :class => 'action index_by_page') %>
        <%= link_to("Show", page_path(page, :subject_id => @subject.id), :class => 'action show') %>
        <%= link_to("Edit", edit_page_path(page, :subject_id => @subject.id), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page, :subject_id => @subject.id), :class => 'action delete') %>
      </td>
    </tr>

    <% end %>
  </table>
</div>

<p><i>Find me in app/views/pages/index.html.erb</i></p>

app/views/pages/new.html.erb
<%= link_to("<< Back to Subjects", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages new">

  <h2>Create Page</h2>

  <%= form_for(@page, :url => pages_path(:subject_id => @subject.id)) do |f| %>

<!-- Moved to _form partial....
    <table summary="Page form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Permalink</th>
        <td><%= f.text_field(:permalink) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
      <tr>
        <th>Subject</th>
        <td><%= f.text_field(:subject_id) %></td>
      </tr>
    </table> -->

    <%= render(:partial => 'form', :locals =>{:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>

  <% end %>
</div>

<p><i>Find me in app/views/pages/new.html.erb</i></p>

app/views/pages/show.html.erb
<%= link_to("<< Back to Subjects", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages show">
  <h2>Show Page</h2>

  <table summary="Page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Subject</th>
      <td><%= @page.subject_id %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>

</div>

<p><i>Find me in app/views/pages/show.html.erb</i></p>