config/routes.rb
Rails.application.routes.draw do

  # This is the action for the root route
  root 'public#index'

  get 'public/index'
  # rails doesnt know how to make this a route, so you can tell it with as
  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  # Simple routes since there are no models, DB, etc. for this.
  get 'admin', :to => 'access#menu'
  get 'access/menu'   #index
  get 'access/login'  #new
  post 'access/attempt_login'
  get 'access/logout'


# ~~~> Subjects Routes <~~~
# These routes were provided by default from the rails generate command.
# Using resourceful routes instead.
#  get 'subjects/index'
#  get 'subjects/show'
#  get 'subjects/new'
#  get 'subjects/edit'
#  get 'subjects/delete'

  resources :subjects do

    member do
      get :delete
    end

  end

# ~~~> Pages Routes <~~~~
#  get 'pages/index'
#  get 'pages/show'
#  get 'pages/new'
#  get 'pages/edit'
#  get 'pages/delete'

  resources :pages do

    member do
      get :delete
    end

    collection do
      get :index_by_subject
    end

  end

# ~~~> Section Routes <~~~
#  get 'sections/index'
#  get 'sections/show'
#  get 'sections/new'
#  get 'sections/edit'
#  get 'sections/delete'

  resources :sections do

    member do
      get :delete
    end

    collection do
      get :index_by_page
    end

  end

# ~~~~> Admin User Routes <~~~~
#  get 'admin_user/index'
#  get 'admin_user/new'
#  get 'admin_user/create'
#  get 'admin_user/edit'
#  get 'admin_user/update'
#  get 'admin_user/delete'
#  get 'admin_user/destroy'

  resources :admin_user, :except => 'show' do

    member do
      get :delete
    end

  end


  # simple match routes
  # match "demo/index", :to => "demo#index", :via => :get
  # this is the longer way to write the same.

  # Default route may go away in future versions of Rails.
  # get ':controller(/:action(/:id))'
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
  get 'demo/escape_output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord

  acts_as_list

  include Audit

  # tell ActiveRecord to make a relationship btwn Subject and page
  # has_one :page

  # tell ActiveRecord to make a one to many relationship
  has_many :pages

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, -> { order("position ASC") }
  scope :newest_first, -> { order("created_at DESC") }
  # example with an argument.  Note this did not like -> instead of lambda written out.
  # This asks for |query| as an argument to .seach.
  # Using this example: Subject.search("Initial")
  # Then the where statement ends up looking like: WHERE (name LIKE '%Initial%')
  scope :search, lambda { |query| where(["name LIKE ?", "%#{query}%"]) }

  validates_presence_of :name
  validates_length_of :name, :maximum => 255
  # validate no non-ascii characters.
  # validates_format_of :name, :with => /\A([[:ascii:]])*\z/, :message => "contains non-ascii characters"
  validates :name, format: { :with => /\A([[:ascii:]])*\z/, :message => "contains non-ascii characters" }
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in
  before_action :set_subject_count, :only => [:new, :create, :edit, :update]
  before_action :build_audit_message, :only => [:destroy]
  after_action :build_audit_message, :only => [:create, :update]

  def index
  #  logger.debug("***** Testing the logger from the Subject index. *****")
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new({:name => 'Default'})
  #  @subject_count = Subject.count + 1
  end

  def create
    # Instantiate a new object using form params
    @subject = Subject.new(subject_params)
    # Save the object
    if @subject.save
      # If save succeeds, redirect to the index action.
      # save always returns true or false.
      flash[:notice] = "Subject '#{@subject.name}' created successfully!"
      redirect_to(subjects_path)
    else
      # If the save fails, redisplay the form so the user can correct
      # Render just renders the template with fields populated.
      flash[:error] = "Subject not created!"
    #  @subject_count = Subject.count + 1
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  #  @subject_count = Subject.count
  end

  def update
    # find an object using form params
    @subject = Subject.find(params[:id])
    # Save the object
    if @subject.update_attributes(subject_params)
      # If save succeeds, redirect to the show action.
      # save always returns true or false.
      flash[:notice] = "Subject '#{@subject.name}' updated successfully!"
      redirect_to(subject_path(@subject))
    else
      # If the save fails, redisplay the form so the user can correct
      # Render just renders the template with fields populated.
      flash[:error] = "Subject not saved!"
    #  @subject_count = Subject.count
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    if @subject.destroy
      flash[:notice] = "Subject '#{@subject.name}' destroyed successfully!"
      redirect_to(subjects_path)
    else
      flash[:error] = "Subject not deleted!"
      render('delete')
    end
  end

  private

  def subject_params
    params.required(:subject).permit(:name, :position, :visible, :created_at)
  end

  def set_subject_count
    @subject_count = Subject.count
    if params[:action] == 'new' || params[:action] =='create'
      @subject_count = Subject.count + 1
    end
  end

  def build_audit_message
    @subject ||= @subject = Subject.find(params[:id])
    @subject.write_audit_log("#{session[:username]} performed action #{action_name} on #{controller_name} id ##{@subject.id}, #{@subject.name}")
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Subject form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@subject_count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Created at</th>
    <td><%= f.datetime_select(:created_at, :order => [:month, :day, :year]) %></td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<!-- <h1>Subjects#delete</h1> -->

<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>
  <!-- Can leave the url out, but MUST specify action (delete in this case) -->
  <%= form_for(@subject, :method => 'delete') do |f| %>

    <p> Are you SURE you want to permanently delete this subject?</p>

    <p class="reference-name>"><strong><%= f.object.name %></strong></p>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

<p><i>Find me in app/views/subjects/delete.html.erb</i></p>

app/views/subjects/edit.html.erb
<!-- <h1>Subjects#edit</h1> -->

<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects edit">

  <h2>Update Subject</h2>
  <%= form_for(@subject) do |f| %>

<!-- Moved to _form partial....
    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
    </table>    -->

    <!-- because it knows this is a partial, the underscore is not needed in the name of the view to render.  Have to pass the local varible f as a symbol when it is called. -->
    <%= render(:partial => 'form', :locals =>{:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

  <% end %>

</div>

<p><i>Find me in app/views/subjects/edit.html.erb</i></p>

app/views/subjects/index.html.erb
<% @page_title ="All Subjects" %>

<!-- label controller and action-->
<div class="subjects index">
  <h2>Subjects</h2>

  <%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>

<!--  <%= link_to("Add New Subject", 'subject/new', :class => 'action new') %> -->
  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <!-- This assigns the header row -->
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <!-- This each method will will go through every element in the array and assign it to the local block value |subject|. -->
    <% @subjects.each do |subject| %>
    <tr> <!-- Table row -->
      <td><%= subject.position %></td> <!-- Table data -->
      <td><%= subject.name %></td>
      <!-- Ternary operator.  Short hand for if/else statement. -->
      <!-- first arg evals true / false.  After the ? is the value if true : value if false -->
      <!-- <td class="center"><%= subject.visible ? 'Yes' : 'Nope' %></td> -->
      <!-- Replaced with status_tag -->
      <td class="center"><%= status_tag(subject.visible) %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%= link_to("View Pages", index_by_subject_pages_path(:subject_id => subject.id), :class => 'action index_by_subject') %>
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
        <!-- This is just an example of two other ways to have the same result with link_to -->
        <%#= link_to("Show1 (Broken)", 'subjects/#{subject.id}', :class => 'action show') %>
        <%#= link_to("Show2", {:controller => 'subjects', :action => 'show', :id => subject.id}, :class => 'action show') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

<p><i>Find me in app/views/subjects/index.html.erb</i></p>

app/views/subjects/new.html.erb
<!-- <h1>Subjects#new</h1>-->

<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">

  <h2>Create Subject</h2>
  <!-- form_for(@subject, :url => subjects_path, :method => 'post') do |f| -->
  <!-- url and method valid, but unnecessary with form_for helper -->
  <%= form_for(@subject) do |f| %>

<!-- Moved to _form partial....
    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
    </table>   -->

    <!-- because it knows this is a partial, the underscore is not needed in the name of the view to render.  Have to pass the local varible f as a symbol when it is called. -->
    <%= render(:partial => 'form', :locals =>{:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>

</div>

<p><i>Find me in app/views/subjects/new.html.erb</i></p>

app/views/subjects/show.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>

<p><i>Find me in app/views/subjects/show.html.erb</i></p>