config/routes.rb
Rails.application.routes.draw do

  # This is the action for the root route
  root 'public#index'

  get 'public/index'
  # rails doesnt know how to make this a route, so you can tell it with as
  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  # Simple routes since there are no models, DB, etc. for this.
  get 'admin', :to => 'access#menu'
  get 'access/menu'   #index
  get 'access/login'  #new
  post 'access/attempt_login'
  get 'access/logout'


# ~~~> Subjects Routes <~~~
# These routes were provided by default from the rails generate command.
# Using resourceful routes instead.
#  get 'subjects/index'
#  get 'subjects/show'
#  get 'subjects/new'
#  get 'subjects/edit'
#  get 'subjects/delete'

  resources :subjects do

    member do
      get :delete
    end

  end

# ~~~> Pages Routes <~~~~
#  get 'pages/index'
#  get 'pages/show'
#  get 'pages/new'
#  get 'pages/edit'
#  get 'pages/delete'

  resources :pages do

    member do
      get :delete
    end

    collection do
      get :index_by_subject
    end

  end

# ~~~> Section Routes <~~~
#  get 'sections/index'
#  get 'sections/show'
#  get 'sections/new'
#  get 'sections/edit'
#  get 'sections/delete'

  resources :sections do

    member do
      get :delete
    end

    collection do
      get :index_by_page
    end

  end

# ~~~~> Admin User Routes <~~~~
#  get 'admin_user/index'
#  get 'admin_user/new'
#  get 'admin_user/create'
#  get 'admin_user/edit'
#  get 'admin_user/update'
#  get 'admin_user/delete'
#  get 'admin_user/destroy'

  resources :admin_user, :except => 'show' do

    member do
      get :delete
    end

  end


  # simple match routes
  # match "demo/index", :to => "demo#index", :via => :get
  # this is the longer way to write the same.

  # Default route may go away in future versions of Rails.
  # get ':controller(/:action(/:id))'
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
  get 'demo/escape_output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  # We changed the table name from User in a different migration.
  # So if this was still file and class was still called User we would need to do this:
  # self.table_name = "admin_users"
  # .... Instead, we just changed the name of the class and file.


  has_secure_password

  has_and_belongs_to_many :pages
  has_many :section_edits
  has_many :sections, :through => :section_edits

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
  FORBIDDEN_USERNAMES = ['littlebopeep', 'humptydumpty', 'marymary']

  scope :sorted, -> { order("last_name ASC", "first_name ASC") }

# long form validations, replaced with sexy validations below.
#  validates_presence_of :first_name
#  validates_length_of :first_name, :maximum => 25
#  validates_presence_of :last_name
#  validates_length_of :last_name, :maximum => 50
#  validates_presence_of :username
#  validates_length_of :username, :within => 8..25
#  validates_uniqueness_of :username
#  validates_presence_of :email
#  validates_length_of :email, :maximum => 100
#  validates_format_of :email, :with => EMAIL_REGEX
#  validates_confirmation_of :email

# sexy validations
  validates :first_name, :presence => true, :length => { :maximum => 25 }
  validates :last_name, :presence => true, :length => { :maximum => 50 }
  validates :username, :presence => true, :length => { :within => 5..25 }, :uniqueness => true
  validates :email, :presence => true, :length => { :maximum => 100 }, :format => EMAIL_REGEX, :confirmation => true

  validate :username_is_allowed
  validate :no_new_users_on_tuesday, :on => :create

  def name
    "#{first_name} #{last_name}"
    # Or: first_name + ' ' + last_name
    # Or: [first_name, last_name].join(' ')
  end

  private

  def username_is_allowed
    if FORBIDDEN_USERNAMES.include?(username)
      errors.add(:username, "has been restricted from use.")
    end
  end

  def no_new_users_on_tuesday
    if Time.now.wday == 2
      errors.add(:base, "No new users on Tuesdays.")
    end
  end
end

app/controllers/admin_user_controller.rb
class AdminUserController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in

  def index
    @adminusers = AdminUser.sorted
  end

  def new
    @adminuser = AdminUser.new
  end

  def create
    @adminuser = AdminUser.new(adminuser_params)
    if @adminuser.save
      flash[:notice] = "User '#{@adminuser.name}' created successfully!"
      redirect_to(admin_user_index_path)
    else
      flash[:error] = "User not created!"
      render('new')
    end
  end

  def edit
    @adminuser = AdminUser.find(params[:id])
  end

  def update
    @adminuser = AdminUser.find(params[:id])
    if @adminuser.update_attributes(adminuser_params)
      flash[:notice] = "User '#{@adminuser.name}' updated successfully!"
      redirect_to(admin_user_index_path)
    else
      flash[:error] = "User not saved!"
      render('edit')
    end
  end

  def delete
    @adminuser = AdminUser.find(params[:id])
  end

  def destroy
    @adminuser = AdminUser.find(params[:id])
    if @adminuser.destroy
      flash[:notice] = "User '#{@adminuser.name}' destroyed successfully!"
      redirect_to(admin_user_index_path)
    else
      flash[:error] = "User not destroyed"
      render('delete')
    end
  end

  private

  def adminuser_params
    params.required(:admin_user).permit(:first_name, :last_name, :username, :email, :password)
  end


end

app/helpers/admin_user_helper.rb
module AdminUserHelper
end

app/views/admin_user/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Admin User form fields">
  <tr>
    <th><%= f.label(:first_name) %></th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:last_name) %></th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:username) %></th>
    <td><%= f.text_field(:username) %></td>
  </tr>
  <tr>
    <th><%= f.label(:email) %></th>
    <td><%= f.text_field(:email) %></td>
  </tr>
  <tr>
    <th><%= f.label(:password) %></th>
    <td><%= f.password_field(:password, placeholder: '********') %></td>
  </tr>

</table>

app/views/admin_user/delete.html.erb
<% @page_title ="Delete Admin User" %>

<%= link_to("<< Back to List", admin_user_index_path, :class => 'back-link') %>

<div class="adminusers delete">
  <h2>Delete Admin User</h2>
  <!-- Can leave the url out, but MUST specify action (delete in this case) -->
  <%= form_for(@adminuser, :method => 'delete') do |f| %>

    <p> Are you SURE you want to permanently delete this Admin User?</p>

    <p class="reference-name>"><strong><%= f.object.name %></strong></p>

    <div class="form-buttons">
      <%= f.submit("Delete User") %>
    </div>

  <% end %>

app/views/admin_user/edit.html.erb
<% @page_title ="Edit Admin User" %>

<%= link_to("<< Back to List", admin_user_index_path, :class => 'back-link') %>

<div class="adminusers edit">

  <h2>Update Admin User</h2>
  <%= form_for(@adminuser) do |f| %>

    <%= render(:partial => 'form', :locals =>{:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update User") %>
    </div>

  <% end %>

</div>

app/views/admin_user/index.html.erb
<% @page_title ="All Admin Users" %>

<%= link_to("<< Back to Menu", admin_path, :class => 'back-link') %>
<!-- label controller and action-->
<div class="adminusers index">
  <h2>Admin Users</h2>

  <%= image_tag('plus_sign.png', :size => '11x11', :alt => '+') %>

<!--  <%= link_to("Add New Subject", 'subject/new', :class => 'action new') %> -->
  <%= link_to("Add New Admin User", new_admin_user_path, :class => 'action new') %>

  <table class="listing" summary="AdmimUser list">
    <!-- This assigns the header row -->
    <tr class="header">
      <th>#</th>
      <th>Last Name</th>
      <th>First name</th>
      <th>Name</th>
      <th>Username</th>
      <th>Email Address</th>
    </tr>

    <% @adminusers.each do |adminuser| %>
    <tr> <!-- Table row -->
      <td><%= adminuser.id %></td> <!-- Table data -->
      <td><%= adminuser.last_name %></td>
      <td><%= adminuser.first_name %></td>
      <td><%= adminuser.name %></td>
      <td><%= adminuser.username %></td>
      <td><%= mail_to(adminuser.email) %></td>
      <td class="actions">
        <%= link_to("Edit", edit_admin_user_path(adminuser), :class => 'action edit') %>
        <%= link_to("Delete", delete_admin_user_path(adminuser), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

<p>Find me in app/views/admin_user/index.html.erb</p>

app/views/admin_user/new.html.erb
<% @page_title ="Create Admin User" %>

<%= link_to("<< Back to List", admin_user_index_path, :class => 'back-link') %>

<div class="adminusers new">

  <h2>Create Admin User</h2>
  <!-- Had to specify the url.  It wanted to use 'admin_users_path' with the helper, probably because I specified admin_users when I created the controller. -->
  <%= form_for(@adminuser, :url => admin_user_index_path) do |f| %>

    <%= render(:partial => 'form', :locals =>{:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create User") %>
    </div>

  <% end %>

</div>