config/routes.rb
Rails.application.routes.draw do

  # This is the action for the root route
  root 'public#index'

  get 'public/index'
  # rails doesnt know how to make this a route, so you can tell it with as
  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  # Simple routes since there are no models, DB, etc. for this.
  get 'admin', :to => 'access#menu'
  get 'access/menu'   #index
  get 'access/login'  #new
  post 'access/attempt_login'
  get 'access/logout'


# ~~~> Subjects Routes <~~~
# These routes were provided by default from the rails generate command.
# Using resourceful routes instead.
#  get 'subjects/index'
#  get 'subjects/show'
#  get 'subjects/new'
#  get 'subjects/edit'
#  get 'subjects/delete'

  resources :subjects do

    member do
      get :delete
    end

  end

# ~~~> Pages Routes <~~~~
#  get 'pages/index'
#  get 'pages/show'
#  get 'pages/new'
#  get 'pages/edit'
#  get 'pages/delete'

  resources :pages do

    member do
      get :delete
    end

    collection do
      get :index_by_subject
    end

  end

# ~~~> Section Routes <~~~
#  get 'sections/index'
#  get 'sections/show'
#  get 'sections/new'
#  get 'sections/edit'
#  get 'sections/delete'

  resources :sections do

    member do
      get :delete
    end

    collection do
      get :index_by_page
    end

  end

# ~~~~> Admin User Routes <~~~~
#  get 'admin_user/index'
#  get 'admin_user/new'
#  get 'admin_user/create'
#  get 'admin_user/edit'
#  get 'admin_user/update'
#  get 'admin_user/delete'
#  get 'admin_user/destroy'

  resources :admin_user, :except => 'show' do

    member do
      get :delete
    end

  end


  # simple match routes
  # match "demo/index", :to => "demo#index", :via => :get
  # this is the longer way to write the same.

  # Default route may go away in future versions of Rails.
  # get ':controller(/:action(/:id))'
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
  get 'demo/escape_output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<!-- The next line is to allow for a blank subjects... if blank, it will be an empty array to prevent it from blowing up. -->
<% subjects ||= [] %>
<ul>
<% subjects.each do |subject| %>
    <li>
      <%= subject.name %>
      <ul>
      <% subject.pages.visible.sorted.each do |page| %>
        <!-- link_to_unless_current does pretty much what you think it does - prevents a tags if the link is the same as the current page. -->
        <!--   link_to_unless_current(page.name, :action => 'show', :id => page.permalink) %></li> -->
        <!-- Change this to a rails helper after the route was defined in routes.rb -->
        <li><%= link_to_unless_current(page.name, public_show_path(page.permalink)) %></li>
      <% end %>
      </ul>
    </li>
   <% end %>
  </ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- double pipes mean 'if blank' -->
    <title>Simple CMS: <%= @page_title || "Admin Area" %></title>
    <!-- Replaced with the style sheet lin tag
    <style>
      span.status { display: block; width: 10px; height: 10px; margin: 0.25em auto; padding: 0; border: 1px solid #000000; }
      span.status.true { background: green; color: green; }
      span.status.false { background: red; color: red; }
    </style> -->
    <%= stylesheet_link_tag('admin', :media =>'all') %>
  </head>

  <body>

    <div id="header">
      <h1>Simple CMS Admin</h1>
    </div>

    <div id="main">
  <!-- the ! before flash means opposite of.  This is saying if not blank -->
      <% if !flash[:notice].blank? %>
        <div class="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>

  <% if !flash[:error].blank? %>
    <div class="error">
      <strong><%= flash[:error] %></strong>
    </div>
  <% end %>

    <div id="content">
    <!-- before yield -->

      <%= yield %>

    <!-- after yield -->
    </div>

    <div id="footer">
      <%= link_to("Public Index", root_path) %> ~~
      Admin Only -->
      <%= link_to("LOGOUT", access_logout_path) %> ~~
      <%= link_to("Admin Users", admin_user_index_path) %> ~~
      <%= link_to("Subject Index", subjects_path) %> ~~
      <%= link_to("Pages Index", pages_path) %> ~~
      <%= link_to("Sections Index", sections_path) %>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag('application', media: 'all') %>
    <%= javascript_include_tag('application') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- double pipes mean 'if blank' -->
    <title>Simple CMS<%= " | #{@page_title}" if @page_title %></title>
    <!-- Replaced with the style sheet lin tag
    <style>
      span.status { display: block; width: 10px; height: 10px; margin: 0.25em auto; padding: 0; border: 1px solid #000000; }
      span.status.true { background: green; color: green; }
      span.status.false { background: red; color: red; }
    </style> -->
    <%= stylesheet_link_tag('public', :media =>'all') %>
  </head>

  <body>

    <div id="header">
      <h1>Simple CMS</h1>
    </div>

    <div id="main">

      <div id="navigation">
        <%= render(:partial => 'layouts/navigation', :locals => { :subjects => @subjects}) %>
      </div>

      <div id="content">
      <!-- before yield -->
        <%= yield %>
      <!-- after yield -->
      </div>

      </div class="clear"></div>

    </div>

    <div id="footer">
      <%= link_to("Public Index", root_path) %> ~~
      Admin Only -->
      <%= link_to("Subject Index", subjects_path) %> ~~
      <%= link_to("Pages Index", pages_path) %> ~~
      <%= link_to("Sections Index", sections_path) %>
    </div>

  </body>
</html>